# Downloader settings
# Root directory for downloads (relative to project root allowed)
output_root = "downloads"

# File with links to download (one URL per line). Relative to project root allowed
links_file = "links.txt"
